spring:
  datasource:
    username: root
    url: jdbc:h2:file:./database/db
    driver-class-name: org.h2.Driver
    password: root
  application:
    name: erp

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.h2Dialect

server:
  port: '8081'
